- name: Installing MySQL-server
  apt:
    name: mysql-server
    state: present

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Install MySQL-python dependencies
  apt:
    name: 
      - python3-mysqldb
    state: present 

- name: Create MySQL user
  mysql_user:
    name: "{{ DB_USERNAME }}"
    password: "{{DB_PASSWORD}}"
    priv: "*.*:ALL"
    host: "{{DB_SERVER}}"
    state: present

- name: Create database
  mysql_db:
    name: "{{DB_NAME}}"
    state: present

- name: Restore database
  mysql_db:
    name: test_db
    state: import
    target: /home/ubuntu/Node_Project/db.sql