# - name: Install php-fpm
#   apt:
#     name: php-fpm
#     state: present

- name: Install PHP and required extensions
  # become: true
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - php 
    # - php-cli 
    # - php-common 
    - php-fpm 
    - php-mysql 
    # - php-zip 
    # - php-gd 
    # - php-mbstring 
    # - php-curl 
    # - php-xml 
    # - php-bcmath 
    # - openssl 
    # - php-json 
    # - php-tokenizer