---

- hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: 8586-terraform-state 
    ansible_aws_ssm_region: us-east-1
    ansible_aws_ssm_s3_addressing_style: virtual
    ssm_timeout: 3600

    DB_SERVER: localhost
    DB_USERNAME: test_user
    DB_PASSWORD: test_0000
    DB_NAME: test_db

  - name: Update
    tags: always
    apt:
      update_cache: yes
      cache_valid_time: 86400

  roles:
    - git
    - net_tools
    - nginx
    - mysql