name: github_action_to_ec2
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  setup_aws_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      
      - name: Terraform Version
        run: echo "Terraform version=$(terraform --version)"

      - name: Terraform Init
        run: terraform init --backend-config=variables/dev.init.tfvars
        working-directory: infrastructure

      - name: Terraform Plan
        run: terraform plan -var-file="variables/dev.tfvars"
        working-directory: infrastructure
      - name: Terraform Apply
        run: terraform apply -var-file="variables/dev.tfvars" -auto-approve
        working-directory: infrastructure

  setup_ansible:
    runs-on: ubuntu-latest
    needs: setup_aws_terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      # - name: Install ansible requirements
      #   run: pip3 install -r ansible/requirements.txt

      - name: Ensure botocore and boto3 modules are installed
        run : pip install boto3 botocore

      - name: Install ansible
        run: pip install ansible

      - name: Ansible graph
        run: ansible-playbook -i aws_ec2.yml configure.yml --graph

      - name: Run Ansible Playbook
        run: ansible-playbook -i aws_ec2.yml configure.yml
        working-directory: ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: false