name: github_action_to_ec2
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  setup_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform-wrapper: false
      
      - name: Terraform Version
        run: echo "Terraform version=$(terraform --version)"

      - name: Terraform Basic Infra Init
        run: terraform init
        working-directory: infrastructure/Terraform-Basic-Infrastructure-Without-EC2

      - name: Terraform Basic Infra Plan
        run: terraform plan
        working-directory: infrastructure/Terraform-Basic-Infrastructure-Without-EC2

      - name: Terraform Basic Infra Apply
        run: terraform apply -auto-approve
        working-directory: infrastructure/Terraform-Basic-Infrastructure-Without-EC2
