name: destroy_github_action_to_ec2
on:
  workflow_dispatch:
jobs:
  setup_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init --backend-config=variables/dev.init.tfvars
        working-directory: infrastructure

      - name: Terraform Destroy
        run: terraform destroy -var-file="variables/dev.tfvars" -auto-approve
        working-directory: infrastructure
